name: Delete image file

on:
  workflow_dispatch:

jobs:
  delete_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete old image
        run: |
          rm Gemini_Generated_Image_3t0hvh3t0hvh3t0h.png

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Remove old image"
          git push
